captainVersion: 4
services:
    $$cap_appname:
        image: mongo:$$cap_mongo_version
        command:
            ['mongod', '--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
        volumes:
            - $$cap_appname-db-data:/data/db
            - $$cap_appname-db-config:/data/configdb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: $$cap_mongo_username
            MONGO_INITDB_ROOT_PASSWORD: $$cap_mongo_password
        healthcheck:
            test: >
                echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0', members:[{_id:0, host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
            interval: 5s
            timeout: 30s
            start_period: 0s
            retries: 30
        caproverExtra:
            notExposeAsWebApp: 'true'

caproverOneClickApp:
    variables:
        - id: $$cap_mongo_version
          label: MongoDB Version
          defaultValue: '7'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/library/mongo/tags/
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_mongo_username
          label: MongoDB Root Username
          defaultValue: root
          description: Only use alphanumeric characters.
          validRegex: /^([a-zA-Z0-9])+$/
        - id: $$cap_mongo_password
          label: MongoDB Password
          type: password
          required: true
          description: Choose a strong password.
          validRegex: /^\s*\S.*$/
    instructions:
        start: >-
            MongoDB is a cross-platform document-oriented database. Classified as a NoSQL database program, MongoDB uses JSON-like documents with schemas. 

            After installation on CapRover, it will be available as `srv-captain--YOUR_CONTAINER_NAME` at port `27017` to other CapRover apps.

            Enter your MongoDB configuration parameters and click on next. It will take about a minute for the process to finish as the replica set initializes.
        end: >-
            MongoDB is deployed and available as `srv-captain--$$cap_appname:27017` to other apps. 

            For example, with Node.js using Mongoose:

            ```javascript
            mongoose.connect('mongodb://srv-captain--$$cap_appname/mydatabase?authSource=admin', {
              user: '$$cap_mongo_username',
              pass: '$$cap_mongo_password',
              useNewUrlParser: true,
              useUnifiedTopology: true,
              replicaSet: 'rs0'
            });
            ```
    displayName: MongoDB
    isOfficial: true
    description: >
        MongoDB is a cross-platform document-oriented database program. Classified as a NoSQL database program, it uses JSON-like documents with schemas.
    documentation: Taken from https://hub.docker.com/r/mongo/

volumes:
    $$cap_appname-db-data:
    $$cap_appname-db-config:
